- docs/guide/why.md
Thanks for starting this project @antfu; I'm really excited to see where it goes. A couple of typo fixes for you 🤓
> docs: fix typos in why.md

- docs/packages/js.md
- migration plugin: `../eslint-plugin-migrate` -> `/guide/migration`
> docs: update deadlink

- packages/eslint-plugin-js/rules/array-element-newline/types.d.ts
- packages/eslint-plugin-js/rules/comma-dangle/types.d.ts
- packages/eslint-plugin-js/rules/func-call-spacing/types.d.ts
- packages/eslint-plugin-js/rules/no-extra-parens/types.d.ts
- packages/eslint-plugin-js/rules/padding-line-between-statements/types.d.ts
- packages/eslint-plugin-js/rules/quote-props/types.d.ts
- packages/eslint-plugin-js/rules/semi/types.d.ts
- packages/eslint-plugin-ts/rules/comma-dangle/types.d.ts
- packages/eslint-plugin-ts/rules/func-call-spacing/types.d.ts
- packages/eslint-plugin-ts/rules/padding-line-between-statements/types.d.ts
- packages/eslint-plugin-ts/rules/semi/types.d.ts
- scripts/migrate.ts
I tested my 2.0.0-beta.0 and found a bug in my script
in 2.0.0-beta.1 I fixed that but and also in @eslint-types/* repo
I now also fixed that bug here
> fix: single schema dts generation

- docs/.vitepress/config.ts
- docs/.vitepress/theme/style.css
- docs/index.md
- docs/package.json
- pnpm-lock.yaml
This PR includes:
- bump to VP rc24
- update styles to fix color constrast (WCAG AA ): we also need to review code blocks, tips, info, warning and danger blocks (if any)
- add footer: license and copyrights
- add `Releases Notes` and `Contributing` links in `version` navbar entry
- add some icons to home features
Should we add local search?
> docs: update styles

- LICENSE
- README.md
- docs/.vitepress/config.ts
This PR also includes the copyright footer in readme file.
> docs: add local search and edit page links

- packages/eslint-plugin-js/rules/one-var-declaration-per-line/one-var-declaration-per-line.test.ts
- packages/eslint-plugin-js/rules/one-var-declaration-per-line/one-var-declaration-per-line.ts
> refactor(js): migrate one-var-declaration-per-line to ts

- packages/eslint-plugin-js/rules/no-extra-parens/no-extra-parens.test.ts
- packages/eslint-plugin-js/rules/no-extra-parens/no-extra-parens.ts
- packages/eslint-plugin-js/utils/ast-utils.ts
> refactor(js): migrate no-extra-parens to ts

- packages/eslint-plugin-js/rules/comma-dangle/comma-dangle.test.ts
- packages/eslint-plugin-js/rules/comma-dangle/comma-dangle.ts
> fix(js/comma-dangle): only add comma when it's in brackets, fix #158

- .github/ISSUE_TEMPLATE/bug_report.yml
Clarify how to see lint results in StackBlitz reproduction
https://github.com/eslint-stylistic/eslint-stylistic/discussions/159
> docs: how to see lint results in reproduction

- docs/guide/config-presets.md
- packages/eslint-plugin-js/configs/index.ts
- packages/eslint-plugin-js/dts/index.d.ts
- packages/eslint-plugin-js/src/index.ts
- packages/eslint-plugin-js/src/plugin.ts
- packages/eslint-plugin-jsx/configs/index.ts
- packages/eslint-plugin-jsx/dts/index.d.ts
- packages/eslint-plugin-jsx/src/index.ts
- packages/eslint-plugin-jsx/src/plugin.ts
- packages/eslint-plugin-plus/configs/index.ts
- packages/eslint-plugin-plus/src/plugin.ts
- packages/eslint-plugin-ts/dts/index.d.ts
- packages/eslint-plugin-ts/src/index.ts
- packages/eslint-plugin-ts/src/plugin.ts
- packages/eslint-plugin/configs/index.ts
- packages/shared/configs-all.ts
- tests/configs/fixtures/input/javascript.js
- tests/configs/fixtures/output/all/javascript.js
- tests/configs/fixtures/output/all/jsx.jsx
- tests/configs/fixtures/output/all/tsx.tsx
- tests/configs/fixtures/output/all/typescript.ts
- tests/configs/fixtures/output/all/vue-ts.vue
- tests/configs/fixtures/output/all/vue.vue
- tests/configs/fixtures/output/default/javascript.js
- tests/configs/fixtures/output/tab-quotes-semi/javascript.js
- tests/configs/preset.test.ts
close #164
Take 2, targeting `main` instead of `dev`
> feat: introduce `all-flat` and `all-extend` config option

- docs/guide/faq.md
- packages/eslint-plugin-js/package.json
- packages/eslint-plugin-jsx/package.json
- packages/eslint-plugin-ts/package.json
- packages/eslint-plugin/package.json
- pnpm-lock.yaml
https://github.com/eslint-stylistic/eslint-stylistic/pull/172#discussion_r1398525315
> docs: correct eslint requirement to `8.40.0`

- docs/.vitepress/components/RuleItem.vue
- docs/.vitepress/components/RuleList.vue
This pull request adds auto-fixable indicator on the rule list. The data is taken from the `metadata` package.
Closes #179 
We can add auto-fixable on each rules, but that takes more time and I think should be done via separate PR.
> feat: add auto fix indicator on rule list

- docs/guide/migration.md
The ESLint team had [announced their deprecation list](https://eslint.org/blog/2023/10/deprecating-formatting-rules/) a little over a month ago, and is now referring to our packages in their docs. This updates our migration guide to reflect that.
> docs: update migration recommendation with ESLint deprecation announcement

- packages/eslint-plugin-js/rules/no-multi-spaces/README.md
- packages/eslint-plugin-js/rules/no-multi-spaces/no-multi-spaces.test.ts
- packages/eslint-plugin-js/rules/no-multi-spaces/no-multi-spaces.ts
- packages/eslint-plugin-js/rules/no-multi-spaces/types.d.ts
fix https://github.com/eslint-stylistic/eslint-stylistic/issues/188
> feat(js/no-multi-spaces): new `includeTabs` option

- packages/eslint-plugin-js/package.json
- packages/eslint-plugin-js/utils/string-utils.ts
- packages/eslint-plugin-ts/package.json
- packages/eslint-plugin-ts/utils/getStringLength.ts
- pnpm-lock.yaml
This PR replaces `graphemer` with `Intl.Segmenter`.
close #219
> feat: replace `graphemer` with `Intl.Segmenter`

- packages/eslint-plugin-js/rules/indent/README.md
The relative link is left over from upstream, but in this repository it leads nowhere.
> fix: link to selectors

- .github/dependabot.yml
#341 & #343 would have been 1 PR
> chore: group `unocss` dependency updates

- packages/eslint-plugin/dts/index.ts
Closes #398 
See the linked issue for a description of the problem.
Since the issue hasn't received any attention in a month, I decide to go ahead and try the solution I suggested there.
Again, you may know of a better solution to this problem, or perhaps you don't like this solution. If so, feel free to close this PR and we can try something else instead. I'm not familiar with this repository so I'm eager to accept correction.
> Make plugin assignable to ESLint.Plugin

- packages/eslint-plugin-ts/rules/indent/indent.ts
Should **NOT** return directly in ts override.
test in #428 
Closes #429
> fix(indent): correct class property initialization

- docs/guide/config-presets.md
Replace "...options **configure** for each rule might be different..." with "...options **configured** for each rule might be different...".
> Fix typo in config-presets.md

- docs/contribute/project-progress.md
Added checkmarks to the current progress milestone for what is completed and what is not.
> docs: update project progress

- packages/eslint-plugin-ts/rules/member-delimiter-style/README.md
> docs(ts/member-delimiter-style): fix spaces

- docs/guide/config-presets.md
- docs/index.md
- packages/eslint-plugin-ts/rules/member-delimiter-style/README.md
> chore: typo

- packages/eslint-plugin-ts/rules/quotes/quotes.test.ts
- packages/eslint-plugin-ts/rules/quotes/quotes.ts
Closes #473 
test(quotes): add some test cases
> fix(quotes): ignore backtick in ts import types

- packages/eslint-plugin-js/rules/indent/indent.ts
- packages/eslint-plugin-ts/rules/indent/indent.test.ts
- packages/eslint-plugin-ts/rules/indent/indent.ts
Add more test cases for decorators
> refactor(indent): simplify the code related to `PropertyDefinition` with decorators

- packages/eslint-plugin-js/rules/indent/indent.ts
- packages/eslint-plugin-ts/rules/indent/indent.test.ts
Add a failing test for #486.
- fix #486
> fix(indent): indentation for argument with decorators

- docs/guide/faq.md
There is a new VS Code ESLint feature which allows you to specifically target auto-fixable rules for modifying severity level: https://github.com/microsoft/vscode-eslint/pull/1841. Updated the docs to include this as a suggestion.
> docs: add `"fixable": true` as a suggestion for removing squiggly lines in VS Code

- docs/guide/migration.md
Unnecessary comma cause diff addition not to show + missing @ before `stylistic`:
> docs: typo

- packages/eslint-plugin/configs/customize.ts
- packages/eslint-plugin/rules/indent/types.d.ts
add the indent option `tabLength` to `customize` function
> feat: add indent option tabLength to customize config

- packages/eslint-plugin/rules/indent/indent._js_.test.ts
- packages/eslint-plugin/rules/indent/indent._js_.ts
Fixes https://github.com/eslint-stylistic/eslint-stylistic/issues/551
Codebases using some kind of html templating like `lit` will have template literals like this all over
```ts
html`
<article
test="test"
class=${clsx('container', {
hide: 'shouldHide',
empty: 'isCollapsed',
})}
>
<div class="header"></div>
</article>
`
```
In current state, this is not linted correctly as reported in the issue. The proposed solution is assuming that indentation should be based on the line with `${` even if it doesn't include only spaces and tabs
One exception is such usages, they are untouched
```ts
`
expression starting with new line ${
'and'} ending on the same line
`
```
https://github.com/eslint-stylistic/eslint-stylistic/issues/551
> feat: Improve indent in template literals

- packages/eslint-plugin/rules/comma-spacing/comma-spacing._ts_.ts
- packages/eslint-plugin/rules/key-spacing/key-spacing._ts_.ts
- packages/eslint-plugin/rules/space-before-blocks/space-before-blocks._ts_.ts
- packages/eslint-plugin/rules/space-before-function-paren/space-before-function-paren._ts_.ts
- packages/eslint-plugin/rules/type-annotation-spacing/type-annotation-spacing._ts_.ts
> refactor: replace deprecated api with new api

- packages/eslint-plugin/rules/quote-props/quote-props._js_.test.ts
- packages/eslint-plugin/rules/quote-props/quote-props._js_.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
This PR modifies the `quote-props` rule to add support for import attributes.
#578
> feat(quote-props): add support for Import Attributes

- packages/eslint-plugin/rules/function-call-spacing/function-call-spacing._ts_.test.ts
- packages/eslint-plugin/rules/function-call-spacing/function-call-spacing._ts_.ts
part of https://github.com/eslint-stylistic/eslint-stylistic/pull/565
> feat(function-call-spacing): support `ImportExpression` in `ts` version

- packages/eslint-plugin/rules/indent/indent._js_.test.ts
- packages/eslint-plugin/rules/indent/indent._js_.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
This PR modifies the indent rule to add support for import attributes.
#578
> feat(indent): add support for Import Attributes

- packages/eslint-plugin/rules/key-spacing/key-spacing._js_.test.ts
- packages/eslint-plugin/rules/key-spacing/key-spacing._js_.ts
- packages/shared/utils/ast/general.ts
This PR modifies the `key-spacing` rule to add support for import attributes.
#578
> feat(key-spacing): add support for Import Attributes

- packages/eslint-plugin/rules/function-call-spacing/function-call-spacing._ts_.test.ts
- packages/eslint-plugin/rules/function-call-spacing/function-call-spacing._ts_.ts
> fix(function-call-spacing): don't remove comments while auto-fixing

- packages/eslint-plugin/rules/max-statements-per-line/README._js_.md
- packages/eslint-plugin/rules/max-statements-per-line/max-statements-per-line._js_.test.ts
- packages/eslint-plugin/rules/max-statements-per-line/max-statements-per-line._js_.ts
- packages/eslint-plugin/rules/max-statements-per-line/types.d.ts
add a new option to ignore specific statement code check
#211
> feat(max-statements-per-line): new option to allow specific statements

- scripts/update.ts
- scripts/update/schema-to-ts.ts
- scripts/update/utils.ts
Due to device limitations, I only tested on Windows and WSL
> fix: fix the `update` script in `Windows`

- packages/eslint-plugin/rules/comma-style/comma-style._js_.test.ts
- packages/eslint-plugin/rules/comma-style/comma-style._js_.ts
fixes #598 
fixes #599 
#598, #599 
~~This PR can be merged after #586 is merged.~~
> fix(comma-style): handles comma after default import and trailing comma

- packages/eslint-plugin/rules/function-call-spacing/function-call-spacing._ts_.ts
Please see the explanation in #616.
Fixes #616.
> fix(function-call-spacing): remove invalid defaults from schema

- docs/guide/migration.md
> docs: correct eslint flat config in migration guide

- packages/eslint-plugin/rules/indent/README._js_.md
> docs(indent): fix incorrect option name

- playground/eslint.config.js
The eslint config before doesn't work in `playground/index.ts`
> chore: fix playground

- packages/eslint-plugin/rules/indent/types.d.ts
- packages/eslint-plugin/rules/key-spacing/README._js_.md
- packages/eslint-plugin/rules/key-spacing/key-spacing._js_.test.ts
- packages/eslint-plugin/rules/key-spacing/key-spacing._js_.ts
- packages/eslint-plugin/rules/key-spacing/key-spacing._ts_.test.ts
- packages/eslint-plugin/rules/key-spacing/key-spacing._ts_.ts
- packages/eslint-plugin/rules/key-spacing/types.d.ts
> feat(key-spacing): add ignoredNodes option

- docs/.vitepress/vite.config.ts
- packages/eslint-plugin/rules/key-spacing/README._js_.md
- remove additional `:::` in `key-spacing`
- fix incorrect breadcrumbs
fixes #577
> docs: fix incorrect breadcrumbs

- packages/eslint-plugin/rules/indent-binary-ops/indent-binary-ops._plus_.test.ts
- packages/eslint-plugin/rules/indent-binary-ops/indent-binary-ops._plus_.ts
Fixes the last case about type-alias in https://github.com/eslint-stylistic/eslint-stylistic/issues/226#issuecomment-2208529955
Closes #469 as all cases in #469 and #226 have been resolved.
> fix(indent-binary-ops): correctly handle `TypeAliasDeclaration`

- packages/eslint-plugin/rules/no-extra-parens/README._js_.md
- packages/eslint-plugin/rules/no-extra-parens/no-extra-parens._js_.test.ts
- packages/eslint-plugin/rules/no-extra-parens/no-extra-parens._js_.ts
- packages/eslint-plugin/rules/no-extra-parens/types.d.ts
> feat(no-extra-parens): introduce `nestedConditionalExpressions` option

- packages/eslint-plugin/rules/comma-style/comma-style._js_.test.ts
- packages/eslint-plugin/rules/comma-style/comma-style._js_.ts
This PR changes the `exceptions` option to empty, enabling syntax checking by default.
close #601 
BREAKING CHANGE: This change will result in more warnings being flagged, and is therefore considered a breaking change if we follow the ESLint core policy.
> feat(comma-style)!: turn off all exceptions option by default

- packages/eslint-plugin/rules/block-spacing/block-spacing._ts_.ts
> refactor: merge `block-spacing`

- packages/eslint-plugin/rules/space-infix-ops/space-infix-ops._ts_.ts
> refactor: merge `space-infix-ops`

- packages/eslint-plugin/rules/space-before-blocks/space-before-blocks._ts_.ts
> refactor: merge `space-before-blocks`

- packages/eslint-plugin/rules/lines-around-comment/lines-around-comment._ts_.ts
> refactor: merge `lines-around-comment`

- packages/eslint-plugin/rules/indent/jsx-indent._js_.test.ts
- packages/eslint-plugin/rules/jsx-curly-brace-presence/jsx-curly-brace-presence._jsx_.test.ts
- packages/eslint-plugin/rules/jsx-indent/jsx-indent._jsx_.test.ts
- packages/eslint-plugin/rules/jsx-props-no-multi-spaces/jsx-props-no-multi-spaces._jsx_.test.ts
- packages/eslint-plugin/rules/jsx-sort-props/jsx-sort-props._jsx_.test.ts
Since we have required v9, some of the conditional expressions about the eslint version in the test cases can be removed.
> test: remove unnecessary ternary expression

- packages/eslint-plugin/rules/quotes/quotes._js_.ts
- packages/eslint-plugin/rules/quotes/quotes._ts_.ts
> refactor: merge `quotes`

- packages/eslint-plugin/rules/object-property-newline/object-property-newline._js_.ts
- packages/eslint-plugin/rules/object-property-newline/object-property-newline._ts_.ts
> refactor: merge `object-property-newline`

- packages/eslint-plugin/rules/object-curly-spacing/object-curly-spacing._js_.ts
- packages/eslint-plugin/rules/object-curly-spacing/object-curly-spacing._ts_.ts
> refactor: merge object-curly-spacing

- packages/eslint-plugin/rules/comma-dangle/comma-dangle._js_.ts
- packages/eslint-plugin/rules/comma-dangle/comma-dangle._ts_.ts
> refactor: `comma-dangle`

- packages/eslint-plugin/rules/object-curly-newline/object-curly-newline._js_.ts
- packages/eslint-plugin/rules/object-curly-newline/object-curly-newline._ts_.ts
> refactor: merge object-curly-newline

- packages/eslint-plugin/rules/brace-style/brace-style._js_.ts
- packages/eslint-plugin/rules/brace-style/brace-style._ts_.ts
> refactor: merge `brace-style`

- packages/eslint-plugin/rules/indent/indent._js_.ts
- packages/eslint-plugin/rules/indent/indent._ts_.ts
part of #482 
Currently, the ignoreNodes option does not work for JSXText and all TS nodes.
Will fix this in another PR.
> refactor: merge `indent`

- packages/eslint-plugin/rules/space-before-blocks/README._ts_.md
enum should be separated by commas
[current](https://eslint.style/rules/ts/space-before-blocks)
correct
> doc(space-before-blocks): typo

- packages/eslint-plugin/rules/semi-spacing/semi-spacing._js_.ts
- packages/eslint-plugin/rules/semi-spacing/semi-spacing._ts_.ts
> refactor: merge `semi-spacing`

- packages/eslint-plugin/rules/no-extra-semi/no-extra-semi._js_.ts
- packages/eslint-plugin/rules/no-extra-semi/no-extra-semi._ts_.ts
> refactor: merge `no-extra-semi`

- packages/eslint-plugin/rules/semi/semi._js_.ts
- packages/eslint-plugin/rules/semi/semi._ts_.ts
> refactor: merge `semi`

- packages/eslint-plugin/rules/quote-props/quote-props._js_.ts
- packages/eslint-plugin/rules/quote-props/quote-props._ts_.ts
> refactor: merge `quote-props`

- packages/eslint-plugin/rules/lines-between-class-members/lines-between-class-members._js_.ts
- packages/eslint-plugin/rules/lines-between-class-members/lines-between-class-members._ts_.ts
> refactor: merge `lines-between-class-members`

- packages/eslint-plugin/rules/jsx-indent/README._jsx_.md
> docs: deprecate `jsx-indent`

- packages/eslint-plugin/rules/key-spacing/key-spacing._js_.ts
- packages/eslint-plugin/rules/key-spacing/key-spacing._ts_.ts
This PR simply copied the JS part to the TS part now.
We still need to spend time to unify the implementation and remove the redundant code.
part of #482 
After this, all the `js` rules have been merged into the `ts` files.
> refactor: merge `key-spacing`

- pnpm-lock.yaml
- pnpm-workspace.yaml
> docs: fix eslint error tip does not display

- docs/packages/js.md
- docs/packages/jsx.md
- docs/packages/plus.md
- docs/packages/ts.md
- packages/eslint-plugin-js/src/index.ts
- packages/eslint-plugin-jsx/src/index.ts
- packages/eslint-plugin-plus/src/index.ts
- packages/eslint-plugin-ts/src/index.ts
This is part of #482 
In the next major, these packages will no longer get new releases
> feat: deprecate sub packages and emit warnings

- packages/eslint-plugin/rules/type-generic-spacing/type-generic-spacing._plus_.ts
> refactor(type-generic-spacing): unify spacing checks

- netlify.toml
- `/packages/:package` -> `/rules` (`/packages/default` -> `/rules`)
- `/rules/:package/:rule` -> `/rules/:rule` (`/rules/default/array-bracket-newline` -> `/rules/array-bracket-newline`)
close https://github.com/eslint-stylistic/eslint-stylistic/issues/810
> docs: redirect sub packages links

- eslint.config.mjs
- packages/eslint-plugin/rules/semi-spacing/semi-spacing.ts
> chore: update ESLint config

- README.md
- docs/.vitepress/uno.config.ts
- docs/components.d.ts
- docs/contribute/guide.md
- docs/contribute/project-progress.md
- docs/guide/config-presets.md
- docs/index.md
- packages/eslint-plugin/README.md
- release-please-config.json
- tsconfig.base.json
- vitest.config.unit.ts
> docs: cleanup outdated information

- scripts/update.ts
normalize path generate on windows
> fix: metadata path generate normalize

- docs/guide/migration.md
- Fix typo in tip for [`migration.md`](https://eslint.style/guide/migration)
- n/a
- n/a
> docs: fix typo in tip for migration.md

- .github/workflows/pkg.new.pr.yml
- README.md
> ci: setup pkg.new.pr

- packages/eslint-plugin/rules/type-generic-spacing/type-generic-spacing.test.ts
- packages/eslint-plugin/rules/type-generic-spacing/type-generic-spacing.ts
> fix(type-generic-spacing): prevent errors caused by empty type params

- packages/eslint-plugin/rules/space-before-function-paren/README.md
- packages/eslint-plugin/rules/space-before-function-paren/space-before-function-paren.ts
This line was added in https://github.com/eslint/eslint/pull/7180.
And forgot to remove in https://github.com/eslint/eslint/issues/8267.
Resolve #682
> docs(space-before-function-paren): remove outdated info

- packages/eslint-plugin/rules/type-annotation-spacing/type-annotation-spacing.test.ts
- packages/eslint-plugin/rules/type-annotation-spacing/type-annotation-spacing.ts
> fix(type-annotation-spacing): handle type annotation in parens

- .github/workflows/pkg.new.pr.yml
> ci: restrict continuous release

- packages/eslint-plugin/configs/disable-legacy.ts
This config doesn't seem to be automatically generated anymore. I'll clean up unused scripts in a new PR.
Resolves #848 
https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/self-closing-comp.md
> fix: correct rule name in `disable-legacy`

- packages/eslint-plugin/rules/operator-linebreak/README.md
> docs(operator-linebreak): add description for "ignore" option earlier

- packages/eslint-plugin/rules/object-curly-spacing/object-curly-spacing._ts_.test.ts
- packages/eslint-plugin/rules/object-curly-spacing/object-curly-spacing.ts
> feat(object-curly-spacing): support `ImportAttribute`

- packages/eslint-plugin/configs/customize.ts
- packages/eslint-plugin/configs/index.ts
- packages/eslint-plugin/rules/eol-last/eol-last.ts
- packages/eslint-plugin/rules/jsx-indent/jsx-indent.ts
- packages/eslint-plugin/rules/line-comment-position/line-comment-position.ts
- packages/eslint-plugin/rules/quotes/quotes.ts
- packages/shared/utils/index.ts
> feat: add `warnOnce` utility for deprecation warnings

- packages/eslint-plugin/rules/array-element-newline/array-element-newline.ts
- packages/eslint-plugin/rules/line-comment-position/line-comment-position.ts
- packages/eslint-plugin/rules/lines-around-comment/lines-around-comment.ts
- packages/eslint-plugin/rules/multiline-comment-style/multiline-comment-style.ts
- packages/eslint-plugin/rules/no-extra-parens/no-extra-parens.ts
- packages/eslint-plugin/rules/spaced-comment/spaced-comment.ts
Replace `filter`+`forEach` chains with single `forEach` loops containing conditional logic.
> perf: reduce array iterations

- packages/eslint-plugin/rules/keyword-spacing/types.d.ts
- packages/eslint-plugin/rules/multiline-comment-style/types.d.ts
> fix: run update, correct type definition

- docs/guide/getting-started.md
Fixing typo - a duplicated word.
> Update getting started document - fix typo

- packages/eslint-plugin/rules/object-curly-spacing/object-curly-spacing.ts
> refactor(object-curly-spacing): simplify import/export checks

- packages/eslint-plugin/rules/keyword-spacing/keyword-spacing.ts
- packages/eslint-plugin/rules/keyword-spacing/types.d.ts
- packages/eslint-plugin/rules/quote-props/quote-props.ts
- packages/shared/utils/ast/general.ts
Related rules:
- keyword-spacing
- quote-props
> feat: update keyword list

- packages/eslint-plugin/rules/type-generic-spacing/type-generic-spacing.test.ts
- packages/eslint-plugin/rules/type-generic-spacing/type-generic-spacing.ts
> fix(type-generic-spacing): allow spaces between class and generic

- packages/eslint-plugin/rules/comma-dangle/README.md
- packages/eslint-plugin/rules/newline-per-chained-call/README.md
- packages/eslint-plugin/rules/object-property-newline/README.md
> docs: use colored diffs in code blocks

- packages/eslint-plugin/rules/multiline-comment-style/multiline-comment-style.ts
> perf(multiline-comment-style): reduce array iterations

- packages/eslint-plugin/rules/padding-line-between-statements/README.md
- packages/eslint-plugin/rules/padding-line-between-statements/padding-line-between-statements._js_.test.ts
- packages/eslint-plugin/rules/padding-line-between-statements/padding-line-between-statements._ts_.test.ts
- packages/eslint-plugin/rules/padding-line-between-statements/padding-line-between-statements.ts
- packages/eslint-plugin/rules/padding-line-between-statements/types.d.ts
Merge #900 first
Resolves #871
> feat(padding-line-between-statements): allow prefix `multiline`/`singleline` for `return` and `type`

- docs/.vitepress/config.ts
> docs: add changelog link

- packages/eslint-plugin/rules/no-extra-parens/no-extra-parens._ts_.test.ts
- packages/eslint-plugin/rules/no-extra-parens/no-extra-parens.ts
> feat(no-extra-parens): handle `TSNonNullExpression` and `TSSatisfiesExpression` as a `TSAssertion`

- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
Something has broken upstream, see https://github.com/rolldown/tsdown/pull/458
> feat: update deps

- .github/workflows/changelog.yml
- .github/workflows/pkg.new.pr.yml
- .github/workflows/release-please.yml
> build: fix publish

- packages/eslint-plugin/rules/indent/types.d.ts
- packages/eslint-plugin/rules/keyword-spacing/types.d.ts
- packages/eslint-plugin/rules/quote-props/quote-props.ts
- shared/utils/ast/general.ts
> fix(quote-props): only check ES3 reserved words for `keywords` option

- packages/eslint-plugin/rules/indent/README.md
> docs(indent): introduce `assignmentOperator`

- docs/.vitepress/components/RuleItem.vue
- docs/.vitepress/components/RuleList.vue
- docs/.vitepress/vite.config.ts
- packages/eslint-plugin/configs/customize.ts
- packages/eslint-plugin/dts/options.d.ts
- packages/metadata/src/metadata.ts
- packages/metadata/src/types.ts
- scripts/update.ts
- scripts/update/utils.ts
- shared/utils/create-rule.ts
You can review #895 directly, it is based on the PR, and should merge this first.
Closes #857
> feat: introduce experimental mechanism

- packages/eslint-plugin/rules/object-curly-spacing/object-curly-spacing._ts_.test.ts
- packages/eslint-plugin/rules/object-curly-spacing/object-curly-spacing.ts
- packages/eslint-plugin/rules/object-curly-spacing/types.d.ts
Merge #897 first
Resolves #893
> feat(object-curly-spacing): introduce `overrides`

- packages/eslint-plugin/rules/generator-star-spacing/README.md
- packages/eslint-plugin/rules/generator-star-spacing/generator-star-spacing.test.ts
- packages/eslint-plugin/rules/generator-star-spacing/generator-star-spacing.ts
- packages/eslint-plugin/rules/generator-star-spacing/types.d.ts
> feat(generator-star-spacing): introduce `shorthand` to override property function shorthands

- shared/utils/index.ts
> ci: don't warn in test

- packages/eslint-plugin/rules/object-curly-spacing/README.md
> docs(object-curly-spacing): introduce `overrides`
