- docs/guide/getting-started.md
- `/contribute/why` is a dead link
> docs: update deadlink

- docs/.vitepress/components/RuleItem.vue
`eslint-plugin-jsx` also includes `eslint-plugin-js`, so jsx rules will jump to js rules.
> fix: docs link

- docs/guide/migration.md
- docs/guide/why.md
- docs/packages/default.md
- docs/packages/js.md
- docs/packages/jsx.md
- docs/packages/ts.md
I noticed these while reading through the docs in preparation for migrating my configs - there's still a few places where the grammar should be improved, but this is at least a start.
> docs: address some general grammar issues

- docs/guide/faq.md
Quick addition to the FAQ page for enabling auto formatting in JetBrain IDEs (Intellij, WebStorm, etc...)
> docs: add auto-format FAQ item for JetBrains

- packages/eslint-plugin-js/dts/rule-options.d.ts
- packages/eslint-plugin-jsx/dts/rule-options.d.ts
- packages/eslint-plugin-ts/dts/rule-options.d.ts
- scripts/migrate.ts
- scripts/prepare.ts
I use `eslint-stylistic` to create my own eslint rules, but it doesn't provide docs link or description, so this pr is aimed to add these.
> feat: add doc comment for rule options

- docs/guide/faq.md
- docs/guide/migration.md
- docs/guide/why.md
Thanks for porting these rules. I noticed a few typos and grammar issues that can be improved during the migration.
> docs: fix grammar issues and improve writing

- packages/eslint-plugin-js/rules/array-bracket-newline/array-bracket-newline.js
- packages/eslint-plugin-js/rules/array-bracket-newline/array-bracket-newline.test.js
Related to: #51 
Migrates to ESM for the rule `array-bracket-newline` under eslint-plugin-js
> refactor(eslint-plugin-js): ESM migration `array-bracket-newline`

- packages/eslint-plugin-js/rules/function-call-argument-newline/README.md
- packages/eslint-plugin-js/rules/function-call-spacing/README.md
- packages/eslint-plugin-js/rules/function-call-spacing/function-call-spacing.js
- packages/eslint-plugin-js/rules/keyword-spacing/README.md
- packages/eslint-plugin-ts/rules/function-call-spacing/README.md
This PR fixes the documentation for `function-call-spacing`.
> docs: fix `function-call-spacing` docs

- packages/eslint-plugin-ts/rules/padding-line-between-statements/padding-line-between-statements.test.ts
- packages/eslint-plugin-ts/rules/padding-line-between-statements/padding-line-between-statements.ts
- packages/eslint-plugin-ts/rules/padding-line-between-statements/types.d.ts
> fix(ts/padding-line-between-statements): support `cjs-import` and `cjs-export` statement type, fix #53

- packages/eslint-plugin-ts/rules/lines-around-comment/lines-around-comment.test.ts
- packages/eslint-plugin-ts/rules/lines-around-comment/lines-around-comment.ts
- packages/eslint-plugin-ts/rules/lines-around-comment/types.d.ts
> fix(ts/lines-around-comment): add missing `afterHashbangComment` in schema, fix #75

- docs/guide/config-presets.md
- packages/eslint-plugin/configs/index.ts
To avoid confusion with `disable-legacy` as the `legacy` can means "Legacy Rules" and "Legacy Config Format". We use `extends` to differentiate the Flat Config and the legacy config format.
> fix(eslint-plugin): rename config `recommended-legacy` to `recommended-extends`

- packages/eslint-plugin-ts/rules/comma-dangle/comma-dangle.test.ts
- packages/eslint-plugin-ts/rules/comma-dangle/comma-dangle.ts
fix #35 
Not sure if it's the best approach, but if it's a comma usage to differentiate generics with JSX Tags, I think it makes sense to handle it as a special case.
> fix(ts/comma-dangle): allow tailing comma in generic in TSX

- docs/guide/faq.md
- packages/eslint-plugin-js/package.json
- packages/eslint-plugin-jsx/package.json
- packages/eslint-plugin-migrate/package.json
- packages/eslint-plugin-ts/package.json
- packages/eslint-plugin/package.json
- pnpm-lock.yaml
We inherited those requirements from the source projects. This PR makes it clear to users.
> docs: specify the Node engine and ESLint version requirement

- packages/eslint-plugin-ts/rules/member-delimiter-style/README.md
- packages/eslint-plugin-ts/rules/space-before-blocks/README.md
- packages/eslint-plugin-ts/rules/type-annotation-spacing/README.md
Typescript documentation used emojis to display incorrect/correct code examples. Now it use the same `::: correct` tag to display the labels in the documentation.
This PR unifies the label `correct` incorrect` that was displayed on the typescript documentation. Now it uses the same label than the Javascript documentation.
Didn't created an issue for it since it was such a small change but if it's requested. I'll do that.
> docs: unify `incorrect/correct` label for typescript documentation

- packages/eslint-plugin-ts/rules/member-delimiter-style/README.md
- packages/eslint-plugin-ts/rules/space-before-blocks/README.md
- packages/eslint-plugin-ts/rules/type-annotation-spacing/README.md
The Javascript documentation has at the start of the code sample a comment line that activates the rule with a specific config. 
I founded it very useful, but was suprised to not see it for the Typescript documentation.
This PR adds it for the Typescript documentation. Also changed a bit of the text in the front of some correct/incorrect examples to be more like the Javascript one (e.g. https://eslint.style/rules/js/lines-around-comment).
> docs: add config as comments within documentations examples

- docs/contribute/guide.md
So later, we could link it in the response to the issue proposing new rules.
> docs: add guideline about adding new rule

- packages/eslint-plugin-plus/dts/rule-options.d.ts
- packages/eslint-plugin-plus/package.json
- packages/eslint-plugin-plus/rules.md
- packages/eslint-plugin-plus/rules/index.ts
- packages/eslint-plugin-plus/rules/type-named-tuple-spacing/README.md
- packages/eslint-plugin-plus/rules/type-named-tuple-spacing/type-named-tuple-spacing.test.ts
- packages/eslint-plugin-plus/rules/type-named-tuple-spacing/type-named-tuple-spacing.ts
- packages/eslint-plugin-plus/rules/type-named-tuple-spacing/types.d.ts
- packages/metadata/src/metadata.ts
This PR introduces a new rule `type-named-tuple-spacing`, ported from https://github.com/antfu/eslint-plugin-antfu/blob/main/src/rules/named-tuple-spacing.ts
Related issue in `ts-eslint`:
- https://github.com/typescript-eslint/typescript-eslint/issues/51
> feat(type-named-tuple-spacing): new rule

- packages/eslint-plugin-ts/rules/padding-line-between-statements/README.md
- packages/eslint-plugin-ts/rules/padding-line-between-statements/padding-line-between-statements.test.ts
- packages/eslint-plugin-ts/rules/padding-line-between-statements/padding-line-between-statements.ts
- packages/eslint-plugin-ts/rules/padding-line-between-statements/types.d.ts
> fix(ts/padding-line-between-statements): add new `function-overload` statement type

- packages/eslint-plugin-js/rules/no-extra-parens/no-extra-parens.ts
- packages/eslint-plugin-ts/rules/no-extra-parens/no-extra-parens.test.ts
- packages/eslint-plugin-ts/rules/no-extra-parens/no-extra-parens.ts
- vitest.config.unit.ts
Fix the uncovered case mentioned in #185.
I added `TSStringKeyword` to `plugin-js` for sharing logic with `plugin-ts`. But it doesn't actually affect the js file.
close https://github.com/eslint-stylistic/eslint-stylistic/issues/185
I did not fix `const x = (a) as string`.
Since `const x = (a)` is not handled in `plugin-js`, I'm not quite sure if there's any concern with that. Please let me know if you know anything about this, or if you're sure it's just a forgotten override.
---
Are there any other cases that have been found but not fixed by this PR?
> fix(ts/no-extra-parens): cover more unnecessary parens case

- packages/eslint-plugin-plus/utils/createRule.ts
At the moment link to rule details in the IDE is broken for `plus` rules. This PR should fix that.
The link on the screenshot leads to `https://eslint.style/rules/ts/indent-binary-ops` page
> Update rules links for "plus" plugin

- docs/guide/config-presets.md
There's a type on the page https://eslint.style/guide/config-presets. Fixed a typo  'Avaible' to 'Available'
> fix typo in config-presets.md

- packages/eslint-plugin-js/rules/padding-line-between-statements/padding-line-between-statements.test.ts
- packages/eslint-plugin-ts/rules/padding-line-between-statements/padding-line-between-statements.test.ts
- packages/eslint-plugin-ts/rules/padding-line-between-statements/padding-line-between-statements.ts
This PR adds [`ExportAllDeclaration`](https://github.com/estree/estree/blob/master/es2015.md#exportalldeclaration) to the list of `export` node types handled by the `padding-line-between-statements` rule. This change effectively aligns the `eslint-plugin-ts` implementation with the (already consistent) implementation of the rule in `eslint-plugin-js`.
An example of code affected by this change:
```js
/*
eslint @stylistic/ts/padding-line-between-statements: [
"error",
{ blankLine: 'never', prev: 'export', next: 'export' }]
*/
export * from "foo";
export * as bar from "bar";
```
This will start to produce an error once the change is applied, like `@stylistic/js/padding-line-between-statements` already does.
> fix(padding-line-between-statements): recognize ExportAllDeclaration nodes

- packages/eslint-plugin-ts/rules/indent/indent.test.ts
- packages/eslint-plugin-ts/rules/indent/indent.ts
The typescript indentation rule produces an error about this code:
```ts
type FooAlias = Foo<
Bar,
Baz
>;
```
complaining that the expected indentation of line 2 and 3 would be 0.
This PR fixes the issue, to handle type parameter instantiations exactly in the same way as type parameter declarations.
> fix(ts/indent): indentation of multiline type parameter instantiations

- packages/eslint-plugin/configs/customize.ts
- tests/configs/fixtures/output/tab-quotes-semi/typescript.ts
Fixes #266 by adjusting the member-delimiter-style rule to use semicolon delimiters when semi is true.
#266
> fix(configs): member-delimiter-style should use semi delimiters when semi is true, fixes #266

- packages/eslint-plugin-js/rules/indent/indent.ts
- packages/eslint-plugin-ts/rules/indent/indent.test.ts
Enumerations are converted to use the base indent `'ObjectExpression, ObjectPattern'` rule, which assumes the first token to be an opening bracket. Passing the available `isOpeningBraceToken` assertion method makes sure it takes the first token it can find that is actually an opening bracket. This mainly fixes cases for people using brace rules that put the opening brace on a newline (i.e., 'allman').
fix: #52
> fix(indent): correctly identify opening brace on enum declaration

- packages/eslint-plugin-js/package.json
- pnpm-lock.yaml
The v1.6.0 is not Node 16 compatible due to espree update from v9.6.1 to v10.0.0
So, this PR is reverting the dependency update of this package only.
[Issue #278 | Maintain compatibility with Node v16](https://github.com/eslint-stylistic/eslint-stylistic/issues/278)
Requires NODE v16 for testing.
> fix: revert espree version bump, fix #278

- packages/eslint-plugin-plus/dts/index.d.ts
In #276 , one of the many TypeScript build errors is:
```sh
node_modules/@stylistic/eslint-plugin-plus/dts/index.d.ts:7:46 - error TS2694: Namespace '"/home/projects/pariwrqko.github/node_modules/@types/eslint/index".ESLint' has no exported member 'RuleModule'.
7   [K in keyof UnprefixedRuleOptions]: ESLint.RuleModule
~~~~~~~~~~
```
This is because in the `dts/index.d.ts` file of eslint-plugin-plus, there is [this line](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/packages/eslint-plugin-plus/dts/index.d.ts#L7):
```ts
[K in keyof UnprefixedRuleOptions]: ESLint.RuleModule
```
In all of the other `dts/index.d.ts` files, that line looks like this:
```ts
[K in keyof UnprefixedRuleOptions]: Rule.RuleModule
```
See the equivalent lines in …
> fix(plus): type error on `RuleMode`

- .github/workflows/autofix.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
[GitHub Actions has deprecated Node 16](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/), so all actions that run on Node 16 need to be updated.
Right now, this warning message shows up on every workflow run:
(see [this run](https://github.com/eslint-stylistic/eslint-stylistic/actions/runs/7942237113) for an example)
All of these actions have new versions that use Node 20. This PR updates those actions to their latest versions.
NA
NA
> chore: update all GitHub Actions to Node 20 versions

- packages/eslint-plugin/dts/rule-options.d.ts
In #276, there are many types errors about how `UnprefixedRuleOptions` is extended:
```sh
node_modules/@stylistic/eslint-plugin/dist/dts/rule-options.d.ts:6:11 - error TS2320: Interface 'UnprefixedRuleOptions' cannot simultaneously extend types 'UnprefixedRuleOptions' and 'UnprefixedRuleOptions'.
Named property ''comma-dangle'' of types 'UnprefixedRuleOptions' and 'UnprefixedRuleOptions' are not identical.
6 interface UnprefixedRuleOptions extends UnprefixedRuleOptions$1, UnprefixedRuleOptions$2, UnprefixedRuleOptions$3, UnprefixedRuleOptions$4 {}
~~~~~~~~~~~~~~~~~~~~~
node_modules/@stylistic/eslint-plugin/dist/dts/rule-options.d.ts:6:11 - error TS2320: Interface 'UnprefixedRuleOptions' cannot simultaneously extend types 'UnprefixedRuleOptions' and 'UnprefixedRuleOptions'.
Named property …
```
> fix: type error on `UnprefixedRuleOptions`

- docs/guide/why.md
- docs/index.md
Change awkward word "one-go" to "one go" on [`/`](https://eslint.style/) and [`/guide/why`](https://eslint.style/guide/why). This sounds more natural in English.
None.
N/A
> Fix awkward phrase in documentation

- packages/eslint-plugin-js/rules/multiline-ternary/README.md
- packages/eslint-plugin-js/rules/multiline-ternary/multiline-ternary.test.ts
- packages/eslint-plugin-js/rules/multiline-ternary/multiline-ternary.ts
- packages/eslint-plugin-js/rules/multiline-ternary/types.d.ts
Add the ignoreJSX option to a multi-line rule.
I want to apply different rules based on parentheses within JSX.
**e.g.**
**_singleline without parentheses_**
> long
```jsx
{a
? <div>blah blah</div>
: <div>blah blah</div>}
```
> short
```jsx
{a ? <div /> : <div />}
```
**_multiline with parentheses_**
```jsx
{a ? (
<div />
) : (
<div />
)}
```
**_a mix of single and multilines_**
```jsx
{a ? (
<div />
) : 0}
```
N/A
> feat(multiline-ternary): add ignoreJSX option

- packages/eslint-plugin-js/rules/spaced-comment/spaced-comment.test.ts
- packages/eslint-plugin-js/rules/spaced-comment/spaced-comment.ts
With `/// <reference types="node" />`, The rule report: "Expected space or tab after '//' in comment  @stylistic/spaced-comment"
Triple-Slash Directives should not be checked. This PR fix it.
#289
> feat(spaced-comment): ignore typescript triple-slash directive

- packages/eslint-plugin-js/rules/no-mixed-operators/README.md
This merge request proposes changes to the documentation page https://eslint.style/rules/js/no-mixed-operators
The current explanation of the rule parameter `groups` is ambiguous w.r.t. what is considered to be 'mixed operators': it is easily misconstrued to mean 'operators of different groups are mixed'.
This merge request proposes a different wording.
It also contains minor changes intended to increase consistency (formatting of operators, order of groups) and one rendering issue (the first occurence of the ternary operator in the current doc is rendered as a smiley because the colon and paren are not formatted as code)
This change is motivated by [my struggle](https://github.com/eslint/eslint/discussions/18201) I had recently while adding and configuring the rule for my project. I …
> docs(no-mixed-operators): clarify rule behavior for parameter 'groups'

- packages/eslint-plugin-js/rules/nonblock-statement-body-position/README.md
This pull request fixes incorrect link for `curly` rule in `nonblock-statement-body-position` rule as `curly` isn't part of `eslint-stylistic`. `curly` will not redirect to the original ESLint rule page.
*Reported on Discord*
- [Page in question](https://eslint.style/rules/js/nonblock-statement-body-position)
- [Current `curly` link](https://eslint.style/rules/js/curly)
> fix(docs): redirect curly to eslint page

- docs/guide/migration.md
- Fixes a typo by changing the `plugin` section name to `plugins`.
- Remove duplicated comma after  `StylisticPlugin.configs['disable-legacy']`.
> fix(typo): migration.md file

- packages/eslint-plugin-jsx/rules/jsx-indent/jsx-indent.test.ts
- packages/eslint-plugin-jsx/rules/jsx-indent/jsx-indent.ts
Currently, there are some issues with jsx-indent, where some indentations are not checked, and there are conflicts with the indent rules. I have added some tests that cannot be passed.
> fix(jsx-indent): conflict between indent and jsx-indent

- packages/eslint-plugin-jsx/rules/jsx-one-expression-per-line/README.md
- packages/eslint-plugin-jsx/rules/jsx-one-expression-per-line/jsx-one-expression-per-line.test.ts
- packages/eslint-plugin-jsx/rules/jsx-one-expression-per-line/jsx-one-expression-per-line.ts
- packages/eslint-plugin-jsx/rules/jsx-one-expression-per-line/types.d.ts
This PR introduces a new option for the jsx-one-expression-per-line rule, where setting it to `{ allow: 'single-line' }` will allow the above scenarios.
Sometimes we may wish to have multiple expressions on a single line, which can make the code more readable. For instance, in scenarios where an icon is required:
```jsx
<p>
Go to page 2 <IconArrow />
</p>
```
All previous options would format this code as:
```jsx
<p>
Go to page 2 
<IconArrow />
</p>
```
The former is more readable and more intuitive.
To avoid being formatted, one can only nest it with `<>...</>`, but this is meaningless.
Similar examples:
```jsx
<div>
This is a <strong>strong</strong> sentence.
</div>
```
```jsx
<Text style={[style.tabName, style.tabNameActive]}>
{tab.name}
(
{tab?.list?.length}
)
</Text>
```
> feat(jsx-one-expression-per-line): allow single line

- packages/eslint-plugin-js/rules/nonblock-statement-body-position/README.md
The documentation of the `nonblock-statement-body-position` rule is pointing to the `curly` rule that has been moved to the main eslint rule so the link became invalid. This PR updates the link to point to the eslint doc instead.
> Fix link of the curly rule

- docs/.vitepress/config.ts
Hi 🙌,
Not real Bug, more UX issue:
In the Documentation, navigate to Header v1.8.0 > click on Contributing > Github Contributing page > return to docs 🥲.
I believe it's unnecessary to direct users to the "Github Contribution page" with this instruction:
"Please refer to https://eslint.style/contribute/guide for more information."
This may negatively impact the user experience.
Thanks 😄,
#382 
before update:
after update:
> docs: fix "Contributing" link

- packages/eslint-plugin-jsx/rules/jsx-one-expression-per-line/jsx-one-expression-per-line.test.ts
- packages/eslint-plugin-jsx/rules/jsx-one-expression-per-line/jsx-one-expression-per-line.ts
‌‌‌‌### Description
`single-line` is currently not being handled correctly:
```jsx
<div><span>foo</span>
</div>
```
It should be formatted as:
```jsx
<div>
<span>foo</span>
</div>
```
This PR adds this test case and fixes the issue.
> fix(jsx-one-expression-per-line): `single-line` only one line break has not been processed

- packages/eslint-plugin-jsx/rules/jsx-one-expression-per-line/README.md
- packages/eslint-plugin-jsx/rules/jsx-one-expression-per-line/jsx-one-expression-per-line.test.ts
- packages/eslint-plugin-jsx/rules/jsx-one-expression-per-line/jsx-one-expression-per-line.ts
- packages/eslint-plugin-jsx/rules/jsx-one-expression-per-line/types.d.ts
This PR is a sync of https://github.com/jsx-eslint/eslint-plugin-react/pull/3677.
> feat(jsx-one-expression-per-line): allow `non-jsx` option

- packages/eslint-plugin-js/rules/quotes/README.md
- packages/eslint-plugin-js/rules/quotes/quotes.test.ts
- packages/eslint-plugin-js/rules/quotes/quotes.ts
- packages/eslint-plugin-js/rules/quotes/types.d.ts
- packages/eslint-plugin-ts/rules/quotes/quotes.test.ts
- packages/eslint-plugin-ts/rules/quotes/quotes.ts
- packages/eslint-plugin-ts/rules/quotes/types.d.ts
This adds a new option `ignoreStringLiterals` to the `quotes` rule. When `ignoreStringLiterals` is enabled, only template literals are reported, not string literals.
Closes #400
N/A
> feat(js): add option `ignoreStringLiterals`

- packages/eslint-plugin-js/rules/quotes/README.md
- packages/eslint-plugin-js/rules/quotes/quotes.test.ts
- packages/eslint-plugin-js/rules/quotes/quotes.ts
- packages/eslint-plugin-ts/rules/quotes/quotes.test.ts
When `avoidEscape: true`, template literals are allowed if  the string contains a quote that would have to be escaped otherwise.
Fixes https://github.com/eslint-stylistic/eslint-stylistic/issues/235
> fix(quotes): allow template literals to avoid escape sequences

- packages/eslint-plugin-ts/rules/indent/indent.test.ts
- packages/eslint-plugin-ts/rules/indent/indent.ts
- packages/eslint-plugin/configs/customize.ts
Resolve the indentation issue for PropertyDefinition when using decorators.
Closes #208
> fix(indent): correct indentation for `PropertyDefinition` with decorators

- .vscode/settings.json
- packages/eslint-plugin-ts/rules/indent/indent.ts
Prevent errors caused by accessing `node.decorators` when it is `undefined` by using optional chaining. This ensures that the code does not break without `ts-parser`.
Closes #421 
Should we decide whether to add ts rules in `@stylistic/eslint-plugin` to determine whether `ts-parser` is used?
> fix(indent): handle undefined `node.decorators` when tsParser is not configured

- packages/eslint-plugin/configs/index.ts
- packages/eslint-plugin/dts/index.ts
- #398 
- #418 (previous PR that failed to solve the issue)
<br/>
<br/>
Here's the issue: the types for ESLint mandate that plugin configs must be a `Record<string, ConfigData | Linter.FlatConfig | Linter.FlatConfig[]>`. This means that all members must be config objects.
However, the `stylistic` plugin tries to include a function in the configs - the `customize()` method. By doing so, giving the plugin to ESLint makes TypeScript explode.
<br/>
<br/>
The easiest solution? Just remove `customize()` from the configs object and include it as a separate export of the package. This would make the `stylistic` plugin normal and perfectly fit the types.
However, this would be a breaking change and require a major version bump to 3.0.0. And it would be undoing the original intent of the project …
> fix: make plugin assignable to ESLint.Plugin (again)

- packages/eslint-plugin-js/rules/indent/indent.ts
- packages/eslint-plugin-ts/rules/indent/indent.test.ts
> fix(indent): correct indentation in chained methods calls with generics

- packages/eslint-plugin-plus/rules/indent-binary-ops/indent-binary-ops.test.ts
- packages/eslint-plugin-plus/rules/indent-binary-ops/indent-binary-ops.ts
fix(plus/indent-binary-ops): considring `||` and `&&`
chore: correct the judgement on `ts type alias`
Closes #406
> fix(plus/indent-binary-ops): considring `||` and `&&`

- packages/eslint-plugin-js/rules/indent/indent.test.ts
- packages/eslint-plugin-ts/rules/indent/indent.test.ts
Class property initialization in next line has broken expected indentation.
Breaking change: #416.
Issue: #429.
This is a failing test to demonstrate broken indentation for property initializer.
> test(indent): add tests

- packages/eslint-plugin-js/rules/array-element-newline/README.md
- packages/eslint-plugin-js/rules/array-element-newline/array-element-newline.test.ts
- packages/eslint-plugin-js/rules/array-element-newline/array-element-newline.ts
- packages/eslint-plugin-js/rules/array-element-newline/types.d.ts
The rule array-element-newline doesn't allow combining the `"consistent"` and `{ "multiline": true }` options.
The `{ "multiline": true }` is excellent for readability.
But with singleline values, it entirely forbid having newlines between elements.
Yet it's also quite helpful for readability with long values or some nested arrays.
With `{ "multiline": true }`, this is invalid.
```js
const urls = [
"https://www.example.com/path/to/something",
"https://www.example.com/path/to/something/else",
"https://www.example.com/path/to/an/other/thing",
];
const matrix = [
[0, 1, 2],
[3, 4, 5],
[6, 7, 8],
];
```
None here, but I opened this very issue on the eslint github back in 2020 before the split occured.
At the time, stylistic rules were frozen.
https://github.com/eslint/eslint/issues/13818
This …
> feat(js/array-element-newline): options multiline and consistent combination

- packages/eslint-plugin-plus/rules/type-generic-spacing/type-generic-spacing.test.ts
- packages/eslint-plugin-plus/rules/type-generic-spacing/type-generic-spacing.ts
fixes #438 
Consider parentheses between `node.constraint/name` and `node.default`, e.g. `type Foo<T = (string | number)> = T`
#438
> fix(type-generic-spacing): consider parentheses

- packages/eslint-plugin-js/rules/indent/indent.test.ts
- packages/eslint-plugin-js/rules/indent/indent.ts
As far as I know, `no-mixed-spaces-and-tabs` does not provide auto-fix, I don't know when they would conflict. At the same time, this prevents the `indent` rule from fixing errors when tabs and spaces are mixed.
I tested it in my ESLint config, it works fine.
https://github.com/hyoban/eslint-config-hyoban/blob/5b6a5301b9c1db0f2daa8605e4c30f92b20f4abb/patches/%40stylistic__eslint-plugin-js%402.6.0-beta.0.patch
> fix(indent): handle mixed spaces and tabs

- packages/eslint-plugin-ts/rules/member-delimiter-style/README.md
fixes #404
Removed weird non-working formatting for a side-note
#404
> docs: fix note block display

- packages/eslint-plugin-js/rules/arrow-parens/arrow-parens.test.ts
- packages/eslint-plugin-js/rules/arrow-parens/arrow-parens.ts
- packages/eslint-plugin-js/test-utils/parsers/arrow-parens/optional-parameter.js
Closes #498 
Should we continue to test this way?
It uses some immutable files as parsing results, which cannot be verified with the latest version of parser.
At the same time, this requires us to keep these files in the repo. I think this is unnecessary.
> fix(arrow-parens): wrong parens removal with optional parameter

- package.json
- packages/eslint-plugin-ts/package.json
- packages/eslint-plugin-ts/rules/type-annotation-spacing/type-annotation-spacing.test.ts
- packages/eslint-plugin-ts/rules/type-annotation-spacing/type-annotation-spacing.ts
- packages/eslint-plugin-ts/rules/type-annotation-spacing/types.d.ts
- pnpm-lock.yaml
Close #503 
bump `@typescript-eslint/utils` as `TSSatisfiesExpression` is missing in the previous version's `createRule`.
> fix(type-annotation-spacing): consider spacing around `as` and `satisfies` operator

- packages/eslint-plugin/rules/keyword-spacing/keyword-spacing._js_.ts
- packages/eslint-plugin/rules/keyword-spacing/keyword-spacing._ts_.test.ts
- packages/eslint-plugin/rules/keyword-spacing/keyword-spacing._ts_.ts
- packages/eslint-plugin/rules/keyword-spacing/types._js_.d.ts
- packages/eslint-plugin/rules/keyword-spacing/types._ts_.d.ts
- packages/eslint-plugin/rules/keyword-spacing/types.d.ts
- packages/eslint-plugin/rules/type-annotation-spacing/type-annotation-spacing._ts_.test.ts
- packages/eslint-plugin/rules/type-annotation-spacing/type-annotation-spacing._ts_.ts
- packages/eslint-plugin/rules/type-annotation-spacing/types.d.ts
> fix: move spacing rules about `as` and `satisfies` from `type-annontation-spacing` to `keyword-spacing`

- packages/eslint-plugin/rules/quotes/quotes._js_.test.ts
- packages/eslint-plugin/rules/quotes/quotes._js_.ts
- packages/eslint-plugin/rules/quotes/quotes._ts_.test.ts
only when `allowTemplateLiterals` set true, allow template literals to avoid escape sequences 
close #542
> fix(quotes): quotes options execute `allowTemplateLiterals` first then `avoidEscape`

- packages/eslint-plugin/rules/jsx-closing-tag-location/README._jsx_.md
- packages/eslint-plugin/rules/jsx-closing-tag-location/jsx-closing-tag-location._jsx_.test.ts
- packages/eslint-plugin/rules/jsx-closing-tag-location/jsx-closing-tag-location._jsx_.ts
- packages/eslint-plugin/rules/jsx-closing-tag-location/types.d.ts
Add location option to customize indentation in the way of jsx-closing-bracket-location
Reproduction of https://github.com/jsx-eslint/eslint-plugin-react/pull/3777
> feat(jsx/jsx-closing-tag-location): add location option to customize indentation

- packages/eslint-plugin/rules/jsx-closing-bracket-location/jsx-closing-bracket-location._jsx_.test.ts
- packages/eslint-plugin/rules/jsx-closing-bracket-location/jsx-closing-bracket-location._jsx_.ts
because attribute comments are different from jsx comments.  so when the last attribute line is a comment and closing tag should with last attribute at same line, expected location will change to 'line-aligned'
```jsx
// incorrect 'jsx-closing-bracket-location': [1, 'after-props']
<input
// comment
type="text"
// comment
/>
```
```jsx
// correct 'jsx-closing-bracket-location': [1, 'after-props']
<input
// comment
type="text"
// comment
/>
```
close #559
> fix(jsx-closing-bracket-location): should not remove comment in jsx

- packages/eslint-plugin/rules/no-multi-spaces/README._js_.md
- packages/eslint-plugin/rules/no-multi-spaces/no-multi-spaces._js_.test.ts
- packages/eslint-plugin/rules/no-multi-spaces/no-multi-spaces._js_.ts
This PR modifies the `no-multi-spaces` rule to add support for import attributes.
Adds the `ImportAttribute` node type to the default `exceptions` option.
The reason for adding it is to avoid conflicts with the `key-spacing` rule, just like with `Property`.
#578
> feat(no-multi-spaces): add `ImportAttribute` node type to default `exceptions` option

- packages/eslint-plugin-js/rules/func-call-spacing/README.md
- packages/eslint-plugin-ts/rules/func-call-spacing/README.md
Fixes broken links to `function-call-spacing` on these pages:
- https://eslint.style/packages/eslint-plugin-js/rules/func-call-spacing/README#js-func-call-spacing
- https://eslint.style/packages/eslint-plugin-ts/rules/func-call-spacing/README#ts-func-call-spacing
> docs(func-call-spacing): fixing broken links

- packages/eslint-plugin/rules/comma-spacing/comma-spacing._js_.test.ts
- packages/eslint-plugin/rules/comma-spacing/comma-spacing._ts_.test.ts
- packages/eslint-plugin/rules/comma-spacing/comma-spacing._ts_.ts
I explored the rule's history and code comments to find the cause of the conflicting test cases for `comma-spacing`.
Changes:
- allow spacing between comma and closing bracket( ] )
Related links:
- https://github.com/typescript-eslint/typescript-eslint/pull/6938
- https://github.com/eslint-stylistic/eslint-stylistic/blob/main/packages/eslint-plugin/rules/comma-spacing/comma-spacing._js_.ts#L156
- https://eslint.style/rules/default/comma-spacing#rule-details
part of #482
> feat: cross test `comma-spacing`

- packages/eslint-plugin/rules/padding-line-between-statements/README._js_.md
- packages/eslint-plugin/rules/padding-line-between-statements/padding-line-between-statements._js_.test.ts
- packages/eslint-plugin/rules/padding-line-between-statements/padding-line-between-statements._js_.ts
- packages/eslint-plugin/rules/padding-line-between-statements/padding-line-between-statements._ts_.test.ts
- packages/eslint-plugin/rules/padding-line-between-statements/padding-line-between-statements._ts_.ts
- packages/eslint-plugin/rules/padding-line-between-statements/types._js_.d.ts
- packages/eslint-plugin/rules/padding-line-between-statements/types._ts_.d.ts
- packages/eslint-plugin/rules/padding-line-between-statements/types.d.ts
Add support for  `multiline-export` and `singleline-export` to help force newlines just between exported interfaces or types like the example below.
```
export { getCategoryId } from './getCategoryId';
export { getVideoId } from './getVideoId';
export { logDeepLinkLaunchWithCommand } from './logger';
export interface Foo {
foo: number;
}
export interface Bar {
bar: number;
}
export const CLIENT = 'client';
export const STARTUP = 'startup';
export const FOO = 'foo';
export const HELLO = 'hello';
```
See discussion started in https://github.com/eslint-stylistic/eslint-stylistic/discussions/580
> feat(padding-line-between-statements): multiline/singleline-export

- packages/eslint-plugin/rules/indent-binary-ops/indent-binary-ops._plus_.test.ts
- packages/eslint-plugin/rules/indent-binary-ops/indent-binary-ops._plus_.ts
Some of the #576 changes were missing.
```ts
// input
type Type =
| ({
type: 'a';
} & A)
| ({
type: 'b';
} & B)
// output
type Type =
| ({
type: 'a'
} & { a: number })
| ({
type: 'b'
} & { b: number })
// expect
type Type =
| ({
type: 'a';
} & A)
| ({
type: 'b';
} & B)
```
Based on this, if the left token begins with a closing parenthesis, the indentation is not lowered.
https://github.com/eslint-stylistic/eslint-stylistic/pull/576
> fix(indent-binary-ops): disabled to lower the indention when left token start with close bracket

- packages/eslint-plugin/rules/key-spacing/key-spacing._js_.test.ts
- packages/eslint-plugin/rules/key-spacing/key-spacing._js_.ts
> fix(key-spacing): crash for import without attributes when using `align` option

- packages/eslint-plugin/rules/comma-style/README._js_.md
- packages/eslint-plugin/rules/comma-style/comma-style._js_.test.ts
- packages/eslint-plugin/rules/comma-style/comma-style._js_.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
This PR adds support for more syntax to `comma-style` rule.
(I would like to change the default for the `exceptions` option to empty, but that would be a breaking change and I will not do so in this PR.)
close #596
~~The type annotation on ImportExpression#options seems to be missing.~~
~~https://github.com/typescript-eslint/typescript-eslint/issues/10236~~
Done
> feat(comma-style): add support for more syntax

- packages/eslint-plugin/rules/comma-dangle/README._js_.md
- packages/eslint-plugin/rules/comma-dangle/comma-dangle._js_.test.ts
- packages/eslint-plugin/rules/comma-dangle/comma-dangle._js_.ts
- packages/eslint-plugin/rules/comma-dangle/comma-dangle._ts_.ts
- packages/eslint-plugin/rules/comma-dangle/types._js_.d.ts
- packages/eslint-plugin/rules/comma-dangle/types._ts_.d.ts
- packages/eslint-plugin/rules/comma-dangle/types.d.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
This PR modifies the `comma-dangle` rule to add support for import attributes.
Specifically, the rule now check for trailing commas in import attributes and dynamic imports.
(Trailing commas in dynamic imports are allowed since ES2025)
I added `importAttributes` and `dynamicImports` options to specify your preferences for how they behave.
#578
~~The type annotation on `ImportExpression#options` seems to be missing.~~
~~https://github.com/typescript-eslint/typescript-eslint/issues/10236~~
Done
> feat(comma-dangle): add support for Import Attributes

- packages/eslint-plugin/rules/function-call-argument-newline/function-call-argument-newline._js_.test.ts
- packages/eslint-plugin/rules/function-call-argument-newline/function-call-argument-newline._js_.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
This PR modifies the `function-call-argument-newline` rule to add support for import attributes.
https://github.com/eslint-stylistic/eslint-stylistic/issues/578
~~The type annotation on `ImportExpression#options` seems to be missing.~~
~~https://github.com/typescript-eslint/typescript-eslint/issues/10236~~
Done
> feat(function-call-argument-newline): add support for Import Attributes

- packages/eslint-plugin/rules/comma-spacing/comma-spacing._ts_.ts
- packages/eslint-plugin/rules/indent/indent._js_.test.ts
- packages/eslint-plugin/rules/indent/indent._js_.ts
- packages/eslint-plugin/rules/jsx-curly-newline/jsx-curly-newline._jsx_.ts
> fix(indent): consider `CallExpression` when `offsetTernaryExpressions` is true

- packages/eslint-plugin/rules/jsx-wrap-multilines/jsx-wrap-multilines._jsx_.test.ts
- packages/eslint-plugin/rules/jsx-wrap-multilines/jsx-wrap-multilines._jsx_.ts
> fix(jsx-wrap-multilines): keep all text before replacement node parentheses

- docs/packages/ts.md
Tried to follow the [docs for es-lint-plugin](https://eslint.style/packages/ts).
When using the suggested flat config I got this
```sh
Oops! Something went wrong! :(
ESLint: 9.16.0
A config object is using the "parser" key, which is not supported in flat config system.
Flat config uses "languageOptions.parser" to override the default parser.
Please see the following page for information on how to convert your config object into the correct format:
https://eslint.org/docs/latest/use/configure/migration-guide#custom-parsers
If you're not using "parser" directly (it may be coming from a plugin), please see the following:
```
Switching from 
```js
parser: parserTs,
```
to
```js
languageOptions: {
parser: parserTs,
},
```
solved the issue.
Related packages from `package.json`:
``` …
```
> docs: support eslint v9 parser

- packages/eslint-plugin/rules/function-call-spacing/types._ts_.d.ts
- packages/eslint-plugin/rules/function-call-spacing/types.d.ts
- packages/eslint-plugin/rules/indent/README._js_.md
- packages/eslint-plugin/rules/indent/indent._js_.test.ts
- packages/eslint-plugin/rules/indent/indent._js_.ts
- packages/eslint-plugin/rules/indent/types.d.ts
Resolves: https://github.com/eslint-stylistic/eslint-stylistic/issues/633
This PR introduces the new `offsetTernaryExpressionsOffsetCallExpressions` option for `indent` for users to switch back to the behavior in 2.11 before the fix of https://github.com/eslint-stylistic/eslint-stylistic/pull/625
> feat(indent): introduce `offsetTernaryExpressionsOffsetCallExpressions` options

- packages/eslint-plugin/rules/array-bracket-spacing/array-bracket-spacing._js_.ts
- packages/eslint-plugin/rules/block-spacing/block-spacing._js_.ts
- packages/eslint-plugin/rules/comma-spacing/comma-spacing._js_.ts
- packages/eslint-plugin/rules/computed-property-spacing/computed-property-spacing._js_.ts
- packages/eslint-plugin/rules/jsx-curly-spacing/jsx-curly-spacing._jsx_.ts
- packages/eslint-plugin/rules/jsx-equals-spacing/jsx-equals-spacing._jsx_.ts
- packages/eslint-plugin/rules/jsx-one-expression-per-line/jsx-one-expression-per-line._jsx_.ts
- packages/eslint-plugin/rules/jsx-tag-spacing/jsx-tag-spacing._jsx_.ts
- packages/eslint-plugin/rules/keyword-spacing/keyword-spacing._js_.ts
- packages/eslint-plugin/rules/no-extra-parens/no-extra-parens._js_.ts
- packages/eslint-plugin/rules/no-whitespace-before-property/no-whitespace-before-property._js_.ts
- packages/eslint-plugin/rules/object-curly-spacing/object-curly-spacing._js_.ts
- packages/eslint-plugin/rules/rest-spread-spacing/rest-spread-spacing._js_.ts
- packages/eslint-plugin/rules/semi-spacing/semi-spacing._js_.ts
- packages/eslint-plugin/rules/space-before-blocks/space-before-blocks._js_.ts
- packages/eslint-plugin/rules/space-before-function-paren/space-before-function-paren._js_.ts
- packages/eslint-plugin/rules/space-in-parens/space-in-parens._js_.ts
- packages/eslint-plugin/rules/space-infix-ops/space-infix-ops._js_.ts
- packages/eslint-plugin/rules/switch-colon-spacing/switch-colon-spacing._js_.ts
- packages/eslint-plugin/rules/template-tag-spacing/template-tag-spacing._js_.ts
- packages/eslint-plugin/rules/yield-star-spacing/yield-star-spacing._js_.ts
`isSpaceBetweenTokens` has been deprecated in [ESLint v6.7.0](https://github.com/eslint/eslint/releases/tag/v6.7.0) in https://github.com/eslint/eslint/pull/12519.
But it has changed the behavior of the `isSpaceBetweenTokens()` method about `JSXText` tokens that contain only spaces.
Related to:
- https://github.com/eslint/eslint/pull/12519
- https://github.com/eslint/eslint/issues/12614
> refactor: replace deprecated `isSpaceBetweenTokens` with `isSpaceBetween`

- packages/eslint-plugin/rules/quotes/README._js_.md
- packages/eslint-plugin/rules/quotes/quotes._js_.test.ts
- packages/eslint-plugin/rules/quotes/quotes._js_.ts
- packages/eslint-plugin/rules/quotes/quotes._ts_.ts
- packages/eslint-plugin/rules/quotes/types.d.ts
In the quotes rule, allowTemplateLiterals is too complicated to represent as a boolean. Some people want template literals to always be allowed regardless of which quote type has been chosen. Some people want template literals to never be allowed. Some people want template literals to be allowed only if necessary to avoid escaping quotes in a string.
This change deprecates the boolean form of allowTemplateLiterals and adds a new string form that can be `always`, `never`, or `avoidEscape`. This allows users to configure the rule with any of the behaviors described above.
Fixes #554
Relates to #542 and #544
> feat(quotes): Option to allow template literals only to avoid escape

- packages/eslint-plugin/rules/key-spacing/README._js_.md
This resolves a typo in the only README file where I found `/*eslint "`. I believe the other README files are free of this issue.
Based on a comment I made in Pull request : [640](https://github.com/eslint-stylistic/eslint-stylistic/pull/640#issuecomment-2556474515)
A picture is worth more than a description:
Link to the `key-spacing` rule : [documentation](https://eslint.style/rules/js/key-spacing#ignorednodes)
> Corrected `key-spacing` typos in README file

- packages/eslint-plugin/rules/key-spacing/README._js_.md
This resolves a layout issue in the `key-spacing` README file where I should have split the block into two separated correct blocks . Sorry about that.
Based on Pull request [662](https://github.com/eslint-stylistic/eslint-stylistic/pull/662)
A picture is worth more than a description:
> Corrected key-spacing layout issue in README file

- docs/guide/config-presets.md
When using the config factory to add customizations in a flat config, it seems like the options param should include a  `flat` property set to `true` in order to properly return the type `Linter.Config`.
Without the `flat` property, the factory returns `Linter.BaseConfig` which causes type errors in flat configs.
This PR just updates the flat config example in the docs to show that.
https://github.com/eslint-stylistic/eslint-stylistic/blob/dd40b057bcec2309c8c0697429990dee838915c2/packages/eslint-plugin/configs/customize.ts#L15-L17
> docs: add `flat: true` to flat config customize example

- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
This is to unpin `@typescript-eslint` deps back to open-end range, like it was before [v3.0.0](https://github.com/eslint-stylistic/eslint-stylistic/releases/tag/v3.0.0) - to avoid installing two different versions of typescript-eslint in projects using @eslint-stylistic. Even in the pnpm-lock file there were two versions specified next to each other - 8.13.0 and 8.21.0.
I don't know why those dependencies have been pinned in https://github.com/eslint-stylistic/eslint-stylistic/commit/89e075a3de9008d2c24ee988d8eac45125a352a1#diff-18ae0a0fab29a7db7aded913fd05f30a2c8f6c104fadae86c9d217091709794cR32-R33
if there is a reason, please share your findings.
fixes #671
> fix(deps): unpin typescript-eslint deps

- packages/eslint-plugin/rules/type-generic-spacing/type-generic-spacing._plus_.test.ts
- packages/eslint-plugin/rules/type-generic-spacing/type-generic-spacing._plus_.ts
This PR essentially brings the exact same feature than #667, but for type param instantiation, so:
```ts
const val: Array<  number > = []
```
would become:
```ts
const val: Array<number> = []
```
> feat(generic-spacing): remove spaces in type param instantiation

- packages/eslint-plugin-js/package.json
- packages/eslint-plugin-jsx/package.json
- packages/eslint-plugin-plus/package.json
- packages/eslint-plugin-ts/package.json
- packages/eslint-plugin/package.json
- scripts/update/utils.ts
Fix ESM compatibility of `scripts/utils.ts`, without this changes the script does not work as the exports are only named exports but no default export.
Probably a leftover of 3145d5082191505f319e576cc30da51b907c380e by @antfu 
Before this:
> > esno scripts/update.ts && pnpm run lint --fix
>
> /home/ferdinand/Dokumente/Projekte/nextcloud/eslint-stylistic/scripts/update/utils.ts:10
> import config from '../../packages/eslint-plugin/configs/customize'
>        ^
> 
> SyntaxError: The requested module '../../packages/eslint-plugin/configs/customize' does not provide an export named 'default'
>     at ModuleJob._instantiate (node:internal/modules/esm/module_job:180:21)
>     at async ModuleJob.run (node:internal/modules/esm/module_job:263:5)
>     at async onImport.tracePromise.__proto__ …
> chore: Update utils for ESM changes

- packages/eslint-plugin/rules/indent-binary-ops/indent-binary-ops._plus_.test.ts
- packages/eslint-plugin/rules/indent-binary-ops/indent-binary-ops._plus_.ts
This pr fixes a regression due to #645. 
Fixes #692 
This rule needs more test cases to prevent similar issues.
eh, help wanted
> fix(indent-binary-ops): handle `{` for left token check

- packages/eslint-plugin-js/src/index.ts
- packages/eslint-plugin-jsx/src/index.ts
- packages/eslint-plugin-migrate/src/index.ts
- packages/eslint-plugin-plus/src/index.ts
- packages/eslint-plugin-ts/src/index.ts
- packages/eslint-plugin/src/index.ts
- rollup.config.base.mjs
This makes it possible to use v4+ in CJS-contexts with `require(esm)` without any downstream code changes, by adding a special named export that `require(esm)` will favor instead of the usual `{ __esModule: true, default: ... }` result.
Relates to #661
Because of how ESM works compared to CJS, by default `require(esm)` results in an object with the `default export` mapped to a `default` property rather than returning the `default` directly in order to allow access to named exports.
This means that while technically we can now use ESM-only packages in CJS contexts, because `require` is usually expected to be equivalent to importing the `default` it's not quite a "drop-in" because the `require`'er needs to account for the ESM/CJS interop to actually get that `default` value.
To account for …
> feat: add `module.exports` named export for `require(esm)` compatibility

- packages/eslint-plugin/rules/no-extra-parens/no-extra-parens._js_.ts
- packages/eslint-plugin/rules/no-extra-parens/no-extra-parens._ts_.ts
Part of #482 
Some nodes force the child nodes(typically type assertion) to be converted to `SequenceExpression` or `FunctionExpression` to implement functionality quickly.
I will create a new PR to refactor them in the future.
> refactor: merge `no-extra-parens`

- packages/eslint-plugin/rules/member-delimiter-style/README._ts_.md
With `/ts/` suffix there is error:
```
TypeError: Key "rules": Key "@stylistic/ts/member-delimiter-style": Could not find plugin "@stylistic/ts".
```
> In member-delimiter-style README remove /ts/ suffix

- packages/eslint-plugin/rules/member-delimiter-style/README._ts_.md
- packages/eslint-plugin/rules/type-annotation-spacing/README._ts_.md
Some error tip can't display.
In current docs page:
after this commit:
This pr also change the doc of `member-delimiter-style` but we still can't see the error tip. here is the reason #746 . but at the browser elements inspects, we can see the trigger element is added. just it is empty.
> docs: incorrect error tip should display

- packages/eslint-plugin/rules/indent/indent._js_.test.ts
- packages/eslint-plugin/rules/indent/indent._ts_.ts
> fix(indent): handle `ChainExpression` and `AwaitExpression` when `offsetTernaryExpressionsOffsetCallExpressions`

- packages/eslint-plugin/rules/max-len/README._js_.md
The string line not have 80 char length
```
// origin line 77 length will not trigger error even not have option `ignoreStrings`
var longString = 'this is a really really really really really long string!';
// after fix have 91 length, that will trigger eslint error
var longString = 'this is a really really really really really really really long string!';
```
And fix eslint comment error
> docs: fix eslint error

- packages/eslint-plugin/rules/indent/indent._ts_.test.ts
- packages/eslint-plugin/rules/indent/indent._ts_.ts
> fix(indent): wrong PropertyDefinition value offset when ts type have multiple line

- packages/eslint-plugin/rules/keyword-spacing/keyword-spacing._ts_.test.ts
- packages/eslint-plugin/rules/keyword-spacing/keyword-spacing._ts_.ts
- packages/eslint-plugin/rules/keyword-spacing/types._ts_.d.ts
- packages/eslint-plugin/rules/keyword-spacing/types.d.ts
Currently, the `keyword-spacing` rule only checks spacing around the `type` keyword in `import type` declarations.  
It does not handle `export type {}` or `export type *` syntax, resulting in inconsistent spacing behavior.
This PR adds support for spacing checks around the `type` keyword in `export` declarations.
> fix(keyword-spacing): check spaces around the `type` keyword in `export` declarations

- packages/eslint-plugin/rules/object-property-newline/README.md
- packages/eslint-plugin/rules/object-property-newline/object-property-newline._js_.test.ts
- packages/eslint-plugin/rules/object-property-newline/object-property-newline._ts_.test.ts
- packages/eslint-plugin/rules/object-property-newline/object-property-newline.ts
- packages/eslint-plugin/rules/object-property-newline/types.d.ts
Since `allowMultiplePropertiesPerLine` was deprecated from [the time it was migrated upstream](https://github.com/eslint-stylistic/eslint-stylistic/commit/4673a27aa94ca1d57a7e6aa4c8698a8fc4d138d7), I think it's time to remove it.
> feat(object-property-newline)!: remove deprecated option

- packages/eslint-plugin/rules/keyword-spacing/README.md
- packages/eslint-plugin/rules/keyword-spacing/keyword-spacing._js_.test.ts
- packages/eslint-plugin/rules/keyword-spacing/keyword-spacing.ts
- packages/eslint-plugin/rules/space-before-function-paren/README.md
- packages/eslint-plugin/rules/space-before-function-paren/space-before-function-paren._js_.test.ts
- packages/eslint-plugin/rules/space-before-function-paren/space-before-function-paren.ts
- packages/eslint-plugin/rules/space-before-function-paren/types.d.ts
> [!CAUTION]
> BREAKING CHANGE
Handling spacing after the `catch` keyword and the following opening parenthesis (only when parameters are present) in `space-before-function-paren` instead of `keyword-spacing`
close #770 
resolves #681
> feat(space-before-function-paren)!: handle catch clause with param

- eslint.config.mjs
- package.json
- packages/eslint-plugin/package.json
- packages/shared/types/index.ts
- packages/shared/utils/ast.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
This is an experiment to see if we can remove typescript as a peer dependency completely.
We can check the size using pkg.pr.new by opening the PR.
Related to #571
Before: 37MB (plugin size: 776KB) <https://pkg-size.dev/@stylistic/eslint-plugin>
After: 12MB (plugin size: 803KB) <https://pkg-size.dev/https:%2F%2Fpkg.pr.new%2F@stylistic%2Feslint-plugin@838>
> feat: no longer deps on `typescript`

- packages/eslint-plugin/rules/indent/indent._ts_.test.ts
- packages/eslint-plugin/rules/indent/indent.ts
The `indent` rule has special handling for indenting the contents of a function definition’s parameters (in a FunctionDeclaration, FunctionExpression, or ArrowFunctionExpression). However, the method for identifying the closing parenthesis of a function definition’s parameters was incorrect:
https://github.com/eslint-stylistic/eslint-stylistic/blob/aa436b8415fa7fe627468ae1b1c75a5f41fe111d/packages/eslint-plugin/rules/indent/indent.ts#L1500
This is incorrect for functions that include return type annotations—since those come between the end of the parameter list and the start of the function body, the “token before the function body” would be the end of the return type annotation, **not** the end of the parameters as expected.
This too-wide range for the function parameters causes …
> fix(indent): correct handling of return type annotations

- packages/eslint-plugin/rules/semi/README.md
[`no-unexpected-multiline`](https://eslint.org/docs/latest/rules/no-unexpected-multiline) is a rule from eslint core, not this package, which is causing a broken link in the docs.
> chore(semi): `no-unexpected-multiline` is a core rule

- packages/eslint-plugin/rules/jsx-curly-spacing/jsx-curly-spacing.ts
- packages/eslint-plugin/rules/jsx-curly-spacing/types.d.ts
- packages/eslint-plugin/rules/jsx-indent-props/jsx-indent-props.ts
- packages/eslint-plugin/rules/jsx-indent-props/types.d.ts
- packages/eslint-plugin/rules/jsx-max-props-per-line/jsx-max-props-per-line.ts
- packages/eslint-plugin/rules/jsx-max-props-per-line/types.d.ts
- packages/eslint-plugin/rules/multiline-ternary/multiline-ternary.ts
- packages/eslint-plugin/rules/multiline-ternary/types.d.ts
Some rules, for example [jsx-curly-spacing](https://github.com/eslint-stylistic/eslint-stylistic/blob/4a5fe59f528021fa2e6e8f787d2f21a69739391b/packages/eslint-plugin/rules/jsx-curly-spacing/jsx-curly-spacing.ts#L45) allow extra properties to be passed in options object, which should not be allowed. This makes it easier for typos in rule options to go unnoticed.
This PR simply disallows extra properties in rules' schemas which currently allow them.
Touched rules:
- jsx-curly-spacing
- jsx-indent-props
- jsx-max-props-per-line
- multiline-ternary
> fix: disallow extra properties in rule options

- packages/eslint-plugin/rules/multiline-comment-style/README.md
- packages/eslint-plugin/rules/multiline-comment-style/multiline-comment-style.test.ts
- packages/eslint-plugin/rules/multiline-comment-style/multiline-comment-style.ts
- packages/eslint-plugin/rules/multiline-comment-style/types.d.ts
This PR add the following changes to the `multiline-comment-style` rule:
_Exclamation comments_ are block comments which starts with an exclamation mark (`/*! ... */`).
AS IS using `@stylistic/multiline-comment-style: ["error", "starred-block"]` rule with the    following code comment resulted in error: 
```js
Error: Expected a linebreak after '/*'
/*!
* Copyright OpenJS Foundation and other contributors, <www.openjsf.org>
* Copyright (c) 2023-PRESENT ESLint Stylistic contributors
*
* Licensed under the MIT license. See LICENSE file in the project root for details.
*/
```
This PR addresses the issue so that the above code is valid. 
Like `JSDoc` comment, by default, all exclamation comments are also ignored when `bare-block` and `separate-lines` option is used. This PR add a new …
> feat(multiline-comment-style): add support for exclamation comments

- packages/eslint-plugin/rules/no-extra-parens/no-extra-parens._ts_.test.ts
- packages/eslint-plugin/rules/no-extra-parens/no-extra-parens.ts
- packages/shared/utils/ast/general.ts
`TSStringKeyword` only checks the `string` keyword, it's not enough obviously.
This PR adds support for:
``` ts
const x: number = 1;
//     ^^^^^^^^
function foo(x: number): number { return x; }
//            ^^^^^^^^ ^^^^^^^^
```
> feat(no-extra-parens): support part of TS Nodes

- packages/eslint-plugin/rules/indent/indent._ts_.test.ts
- packages/eslint-plugin/rules/indent/indent.ts
Fix incorrect parenthesis positioning specifically when:
- CallExpression contains type arguments
- Type arguments include nested parentheses
- Only occurs in complex type structures like:
```ts
// parentheses inside type argument
func<{ prop: (Type) }>(...)
^
```
Fix: #909
> fix(indent): correctly locate left paren in `CallExpression` with specific type arguments

- packages/eslint-plugin/rules/indent/indent.ts
This change is independent of upstream parser decisions.
I'm implementing a conservative fix here to prevent crashes.
We may revisit this implementation for alignment once the parser's approach finalizes.
#915
https://github.com/typescript-eslint/typescript-eslint/issues/11455
https://github.com/microsoft/TypeScript/issues/62188
> fix(indent): prevent crashes during `JSXFragment` handling

- packages/eslint-plugin/rules/jsx-one-expression-per-line/jsx-one-expression-per-line.test.ts
- packages/eslint-plugin/rules/jsx-one-expression-per-line/jsx-one-expression-per-line.ts
Enhance the auto-fix result.
Input:
```tsx
<div
className='fs-6 col-12 text-danger fw-bold'
>Up to {percent}% Off
</div>
```
Before:
```tsx
<div
className='fs-6 col-12 text-danger fw-bold'
>
Up
to
{percent}
% Off
</div>
```
After:
```tsx
<div
className='fs-6 col-12 text-danger fw-bold'
>
Up to {percent}% Off
</div>
```
Resolves #869
> feat(jsx-one-expression-per-line): enhance the fix result when `allow` is `single-line`

- packages/eslint-plugin/rules/no-extra-parens/README.md
- packages/eslint-plugin/rules/no-extra-parens/no-extra-parens._js_.test.ts
- packages/eslint-plugin/rules/no-extra-parens/no-extra-parens.ts
After #899, some options can simply use [`ignoredNodes`](https://eslint.style/rules/no-extra-parens#ignorednodes) instead; we can just add some examples in the docs.
Options are deprecated in this PR:
- `enforceForArrowConditionals`
- `enforceForNewInMemberExpressions`
- `allowNodesInSpreadElement`
> feat(no-extra-parens): deprecate some options in favor of `ignoredNodes`
